name: release-test
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: t
        run: echo hi
        env:
          S1: ${{ secrets.OTD_BT_P12_B64 }}
